use_frameworks!

platform :ios, '9.0'

target 'ReconhecimentoImg_Example' do
  pod 'ReconhecimentoImg', :path => '../'

  target 'ReconhecimentoImg_Tests' do
    inherit! :search_paths

    
  end
end
